# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
#   build-linux:
#     runs-on: ubuntu-latest
#     env:
#       DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

#     steps:
#     - uses: actions/checkout@v4
#     - name: Setup .NET
#       uses: actions/setup-dotnet@v4
#       with:
#         dotnet-version: 8.0.403
#     - name: Build
#       shell: pwsh
#       run: |
#         Import-Module ./build.psm1 -Force
#         Start-Build -Verbose

  build-windows:
    runs-on: self-hosted
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.403
    - name: Build
      shell: pwsh
      run: |
        Import-Module ./build.psm1 -Force
        Start-Build -Verbose

  # build-macos:
  #   runs-on: macos-latest
  #   env:
  #     DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Setup .NET
  #     uses: actions/setup-dotnet@v4
  #     with:
  #       dotnet-version: 8.0.403
  #   - name: Build
  #     shell: pwsh
  #     run: |
  #       Import-Module ./build.psm1 -Force
  #       Start-Build -Verbose
